#!/bin/bash
#disable all the posix features that make unquoted vars dangerous
set -f
if [ ! -z "$ZSH_VERSION" ] ; then
	setopt sh_word_split
	#for some reason zsh was using a static seed for the randomness
	unset RANDOM
	#RANDOM=`shuf -i 0-10000 -n 1`
fi
ascii=1
for a in "$@"; do
	case "$a" in
	-A)
		ascii=1
	;;
	-a)
		ascii=0
	;;
	esac
done

ENDL='
'
MAX_FRAMESKIP=3
#if it takes this long or less to read input, assume it's
#coming from the buffer and we need to frame
#skip to catch up
MAX_BUFF_WAIT=10

UP='[A'
DOWN='[B'
LEFT='[D'
RIGHT='[C'

C_UP='OA'
C_DOWN='OB'
C_LEFT='OD'
C_RIGHT='OC'

LIGHT='[1m'
DARK='[2m'
CLEAR='[0m'

VOID='  '
if [ "$ascii" -eq 0 ] ; then
	BIT='🔳'
	BOT='──'
	_J='┘'
	L_='└'
	WALL='│'
	CW=2
else 
	BIT='[]'
	BOT='--'
	_J=/
	L_=\\
	WALL='|'
	CW=2
fi

FALLING=
PREVIEW=$FALLING
LANDED=
GHOST=$LIGHT

W=10
H=24
T_SZ=4
paused=0

if [ ! -z "$BASH_VERSION" ] ; then
	read_ch() {
		read -rsN1 "$1"
	}
else
	read_ch() {
		if [ -t 0 ] ; then
			read_ch_old=`stty -g`
			stty -icanon -echo
			eval "$1"'=`dd bs=1 count=1 2>/dev/null`'
			stty $read_ch_old
		else
			eval "$1"'=`dd bs=1 count=1 2>/dev/null`'
		fi
	}
fi

COLOR_PREFIX='[7m'
ORANGE=$COLOR_PREFIX'[33m'
RED=$LIGHT$COLOR_PREFIX'[31m'
GREEN=$LIGHT$COLOR_PREFIX'[32m'
YELLOW=$LIGHT$COLOR_PREFIX'[33m'
BLUE=$LIGHT$COLOR_PREFIX'[34m'
MAGENTA=$LIGHT$COLOR_PREFIX'[35m'
CYAN=$LIGHT$COLOR_PREFIX'[36m'

numTetronis=7
numTetronisM1=6

#check if shell suports $RANDOM
if [ 8$RANDOM -ne 8 ] ; then
	getRandom() {
		echo $(($RANDOM % $numTetronis ))
	}
else
	getRandom() {
		dd if=/dev/urandom count=1 2> /dev/null | cksum | awk '{print $1%'"$numTetronis"'}'
	}
fi
delay=5
minDelay=2
pause() {
	/bin/sleep .$delay
}
decDelay() {
	delay=$(($delay - 1))
}
speedUp() {
	if [ $delay -gt $minDelay ] ; then
		decDelay
		kill -12 "$pid"
	fi
}
upTo() {
	echo "$1" "$2" | awk '{for (i=$1; i<$2; i++) print i}'
}
upToW=`upTo 0 $W`
upToH=`upTo 0 $H`
getRandTetroni() {
	case `getRandom` in
	0)
		echo I
	;;
	1)
		echo J
	;;
	2)
		echo L
	;;
	3)
		echo O
	;;
	4)
		echo S
	;;
	5)
		echo T
	;;
	6)
		echo Z
	;;
	esac
}
getColor() {
	case "$1" in
	O)
		echo "$ORANGE"
	;;
	R)
		echo "$RED"
	;;
	G)
		echo "$GREEN"
	;;
	Y)
		echo "$YELLOW"
	;;
	B)
		echo "$BLUE"
	;;
	M)
		echo "$MAGENTA"
	;;
	C)
		echo "$CYAN"
	;;
	esac
}
tetroni() {
	z=0
	for c in $2 ; do
		x=`expr $z % $T_SZ`
		y=`expr $z / $T_SZ`
		c=`getColor $c`
		eval 'tetroni_'$1_0_${x}_$y'=$c'
		z=`expr $z + 1`
	done
	rotateInto 1 $1_0 $1_1
	rotateInto 1 $1_1 $1_2
	rotateInto 1 $1_2 $1_3
}
newTetroni() {
	tet="$next"
	ang=0
	next=`getRandTetroni`
	Tx=$(($W / 2 - 2))
	Ty=0
	if inBounds ; then :
	else
		display
		echo 'game over'
		exit
	fi
}

render() {
	rY=$Ty
	bringDown	##no_expr##
	By=$Ty
	Ty=$rY

	w=`tput cols`
	h=`tput lines`
	unset lines
	rY=0
	Tx_plus_T_SZ=$(($Tx + $T_SZ))
	Ty_plus_T_SZ=$(($Ty + $T_SZ))
	By_plus_T_SZ=$(($By + $T_SZ))
	for rY in $upToH; do
		line=$WALL
		#flag these as invalid only calculate 
		#them if we need them later down below
		rDy=-1
		rBy=-1
		rX=0
		for rX in $upToW; do
			eval 'rV=$GRID_'${rX}_$rY
			void=1
			#if the rX is inside the box of the tetroni
			if [ "$Tx" -le "$rX" ] && [ "$rX" -lt "$Tx_plus_T_SZ" ] ; then
				#if the rY is inside the box of the tetroni
				if [ "$Ty" -le "$rY" ] && [ "$rY" -lt "$Ty_plus_T_SZ" ] ; then 
					rDx=$(($rX - $Tx))
					if [ $rDy -eq -1 ] ; then
						rDy=$(($rY - $Ty))
					fi
					if eval '[ "$tetroni_'${tet}_${ang}_${rDx}_$rDy'" != "" ]' ; then
						eval 'rV=$FALLING$tetroni_'${tet}_${ang}_${rDx}_$rDy
						rP=$BIT
						void=0
					fi
				fi
				#if the rY is inside the box of where the tetroni is going to land
				if [ $void -eq 1 ] && [ "$By" -le "$rY" ] && [ "$rY" -lt "$By_plus_T_SZ" ] ; then
					rDx=$(($rX - $Tx))
					if [ $rBy -eq -1 ] ; then
						rBy=$(($rY - $By))
					fi
					if eval '[ "$tetroni_'${tet}_${ang}_${rDx}_$rBy'" != "" ]' ; then
						rV=$GHOST
						rP=$BIT
						void=0
					fi
				fi
			fi
			if [ "$void" -eq 1 ] ; then
				if [ "$rV" = "" ] ; then
					rP=$VOID
				else
					rP=$BIT
				fi
			fi
			if [ "$paused" = 1 ] ; then
				rV=
			fi
			line=$line$rV$rP$CLEAR
		done
		line=$line$WALL
		if [ "$rY" -lt "$T_SZ" ] ; then
			rX=0
			while [ "$rX" -lt "$T_SZ" ] ; do
				eval 'rV=$tetroni_'"${next}_0_${rX}_$rY"
				if [ "$rV" = "" ] ; then
					rP=$VOID
				else
					rP=$BIT
				fi
				if [ "$paused" = 1 ] ; then
					rV=
				fi
				line=$line$PREVIEW$rV$rP$CLEAR
			rX=$(($rX + 1))	##no_expr##
			done
		fi
		lines=$lines$line$ENDL
	done
	line=$L_
	rX=0
	while [ "$rX" -lt "$W" ] ; do
		line=$line$BOT
		rX=$(($rX + 1))	##no_expr##
	done
	lines=$lines$line$_J
}
draw() {
	showed=0
	IFS_PREV=$IFS
	IFS=$ENDL
	start=$(( ( $w - $W * $CW ) / 2 ))
	for l in $lines ; do
		if [ "$showed" = 0 ] ; then
			printf %"$start"s "Score: `printf %d "$score"00`"
			showed=1
		elif [ "$showed" = 1 ] ; then
			printf %"$start"s "Lines: $allMatches"
			showed=2
		else
			printf %"$start"s ''
		fi
		printf '%s\n' "$l"
	done
	IFS=$IFS_PREV
}
display() {
	render
	tput cuu $(($H + 1))
	draw
}
fall() {
	if slide 0 1 ; then :
	else
		land
	fi
}
land() {
	lDx=0
	while [ "$lDx" -lt "$T_SZ" ] ; do
		lDy=0
		while [ "$lDy" -lt "$T_SZ" ] ; do
			lX=$(($lDx + $Tx))
			lY=$(($lDy + $Ty))
			eval 'v=$tetroni_'${tet}_${ang}_${lDx}_$lDy
			if [ "$v" != '' ] ; then
				#GRID[lX+lY*W]=$v
				eval "GRID_${lX}_$lY="'$v'
			fi
			lDy=$(($lDy + 1))	##no_expr##
		done
		lDx=$(($lDx + 1))	##no_expr##
	done
	newTetroni
	checkMatch
}
allMatches=0
checkMatch() {
	matches=0
	cmS=1
	cmDy=$(($H - 1))
	cmY=$cmDy
	while [ "$cmY" -ge 0 ] ; do
		rowMatch=1
		cmX=0
		while [ "$cmX" -lt "$W" ] ; do
			if [ "$cmY" != "$cmDy" ] ; then
				eval "GRID_${cmX}_$cmDy="'$GRID_'"${cmX}_$cmY"
				eval "GRID_${cmX}_$cmY="
			fi
			if eval '[ "$GRID_'${cmX}_$cmDy'" = "" ]' ; then
				rowMatch=0
			fi
			cmX=$(($cmX + 1))	##no_expr##
		done
		if [ "$rowMatch" -ne 1 ] ; then
			cmDy=$(($cmDy - 1))
		else
			matches=$(($matches + 1))
		fi
		cmY=$(($cmY - 1))
	done
	preM=$(( $allMatches / 10 ))
	allMatches=$(( $allMatches + $matches ))
	postM=$(( $allMatches / 10 ))
	if [ "$preM" -lt "$postM" ] ; then
		speedUp
	fi
	if [ "$matches" -ne 0 ] ; then
		while [ "$matches" -gt 1 ] ; do
			cmS=$(($cmS * 2))
			matches=$(($matches - 1))
		done
		score=$(($score + $cmS))
	fi
}
inBounds() {
	bDx=0
	while [ "$bDx" -lt "$T_SZ" ] ; do
		bDy=0
		while [ "$bDy" -lt "$T_SZ" ] ; do
			bX=$(($bDx + $Tx))
			bY=$(($bDy + $Ty))
			eval 'bV=$tetroni_'${tet}_${ang}_${bDx}_$bDy
			if [ "$bV" != '' ] ; then
				if [ "$bX" -lt 0 ] || [ "$bX" -ge "$W" ] || [ "$bY" -lt 0 ] || [ "$bY" -ge "$H" ] || eval '[ "$GRID_'${bX}_$bY'" != "" ]' ; then
					return 1
				fi
			fi
			bDy=$(($bDy + 1))	##no_expr##
		done
		bDx=$(($bDx + 1))	##no_expr##
	done
	return 0
}
slide() {
	Tx=$(($Tx + $1))
	Ty=$(($Ty + $2))
	if inBounds ; then :
	else
		Tx=$(($Tx - $1))
		Ty=$(($Ty - $2))
		return 1
	fi
	return 0
}
bringDown() {
	while slide 0 1 ; do
		:
	done
}
rotate() {
	oang=$ang
	ang=$(( ( $ang + 4 + $1 ) % 4 ))
	rotateInto $1 ''
	if inBounds ; then :
	else
		thrash || ang=$oang
	fi
}
thrash() {
	oldTx=$Tx
	oldTy=$Ty

	for thrashDx in -1 0 1 ; do
		for thrashDy in 0 1 ; do
			Tx=$(($oldTx + $thrashDx))
			Ty=$(($oldTy + $thrashDy))
			inBounds && return 0
		done
	done

	Tx=$oldTx
	Ty=$oldTy
	return 1
}
rotateInto() {
	csz=$T_SZ
	s=$(($csz - 1))
	half=$(( ( $csz + 1 ) / 2))
	hsz=$(($csz / 2))
	x=0
	while [ "$x" -lt "$half" ] ; do
		y=0
		while [ "$y" -lt "$hsz" ] ; do
			eval 'val=$tetroni_'$2_${x}_$y
			for i in 0 1 2 3 ; do
				if [ "$1" -ge 1 ] ; then
					oy=$y
					y=$x
					x=$(($s - $oy))
				else
					ox=$x
					x=$y
					y=$(($s - $ox))
				fi
				eval 'pval=$tetroni_'$2_${x}_$y
				eval 'tetroni_'$3_${x}_$y'=$val'
				val=$pval
			done
			y=$(($y + 1))	##no_expr##
		done
		x=$(($x + 1))	##no_expr##
	done
}
togglePause() {
	if [ "$paused" = 0 ] ; then
		paused=1
		obit=$BIT
		BIT=$VOID
		display
		BIT=$obit
	else
		paused=0
		display
	fi
}
tetroni I '
	. C . .
	. C . .
	. C . .
	. C . .
	'
tetroni J '
	. B B .
	. B . .
	. B . .
	. . . .
	'
tetroni L '
	. O O .
	. . O .
	. . O .
	. . . .
	'
tetroni O '
	. . . .
	. Y Y .
	. Y Y .
	. . . .
	'
tetroni S '
	. . . .
	. G G .
	G G . .
	. . . .
	'
tetroni T '
	. . . .
	. M . .
	M M M .
	. . . .
	'
tetroni Z '
	. . . .
	R R . .
	. R R .
	. . . .
	'
ang=0
tet=`getRandTetroni`
next=`getRandTetroni`
newTetroni
render
draw
(
	(
		trap 'READY=1' 10 #sigusr1
		trap 'decDelay' 12 #sigusr2
		READY=0
		while pause ; do
			if [ "$READY" = 1 ] ; then
				printf j
				READY=0
			fi
			#printf $'\a' >&2
		done 
	) &
	#pid is read first and other input is ignored
	#start parsing other input on '.'
	echo $! .
	while read_ch p; do 
		if [ "$p" = '' ] ; then
			read_ch ap
			p=$p$ap
			read_ch ap
			p=$p$ap
		fi
		case "$p" in
		h|"$LEFT")
			printf h
		;;
		j|"$DOWN")
			printf j
		;;
		k|x|"$UP"|"$C_RIGHT")
			printf k
		;;
		r|z|"$C_UP"|"$C_LEFT")
			printf r
		;;
		l|$RIGHT)
			printf l
		;;
		' '|"$C_DOWN")
			printf G
		;;
		p)
			printf p
		;;
		esac
	done 
) | (
	while read_ch p; do
		case "$p" in
		[0-9])
			pid=$pid$p
		;;
		.)
			break
		;;
		esac
	done
	trap 'kill $pid' EXIT
	while read_ch p; do
		if [ "$paused" = 1 ] ; then
			if [ "$p" = p ] ; then
				togglePause
			fi
		else
			case "$p" in
			h)
				slide -1 0
			;;
			j)
				fall
			;;
			k)
				rotate 1
			;;
			l)
				slide 1 0
			;;
			G)
				bringDown
				land
				#speedUp
			;;
			r)
				rotate -1
			;;
			p)
				togglePause
			;;
			esac
		fi
		if [ "$paused" = 0 ] ; then
			display
			#signal other process we're ready for input
			kill -10 "$pid"
		fi
	done
)
